web/faces/controllers.py
import time
from flask import abort, Blueprint, current_app, send_file, render_template, url_for
from flask import make_response, redirect, request

import web.connector as connector

import uuid

faces = Blueprint('faces', __name__, template_folder='templates')

@faces.route('/')
def index():
    sid = connector.new_user(15) # TODO 15 needs to be the MTURK_ID
#    if sid is None:
#        return 'REDIRECT THIS TO MTURK1'
    response = make_response(redirect(url_for('faces.trial',sid=sid)))
    response.set_cookie('timer','1')
    return response

@faces.route('/trial/<sid>')
def trial(sid):
    trial = connector.get_trial(sid)
    if trial is None:
        return 'REDIRECT THIS TO MTURK2'
    return render_template('trial.html',trial=trial)

@faces.route('/response/<sid>/<tid>/<rid>')
def response(sid, tid, rid): # session id, trial id, response id
    check = connector.set_response(sid, tid, rid)
    timer = request.cookies.get('timer')
    print(str(timer))
    return redirect(url_for('faces.trial', sid=sid))

web/faces/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>T-PAMI</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/bootswatch.min.css') }}" /> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
  </head>
<body>
  <div class="container-fluid">
    <div class="jumbotron col-lg-12" style="min-height: 750px;">
      <div class="col-lg-12">
        <h4 style="text-align: center; font-weight: bold;">DO NOT REFRESH ONCE YOU BEGIN</h4>
      </div>
      <hr style="border: 1px solid;" />
      {% block container %}{% endblock %}
    </div>
  </div>

  <div class="footer">
    <br />
    <br />
    <div class="container">
      <p><span class="glyphicon glyphicon-copyright-mark"></span> Brandon RichardWebster | last updated Sat Aug 19 2017 </p>
    </div>
  </div>

  <script src="{{ url_for('static', filename='js/jquery-3.1.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/pamiexp.js') }}"></script>
</body>

web/faces/templates/trial.html
{% extends 'layout.html' %}
{% block container %}


<div id="ProbeID" class="row hidden">
   <div class="col-lg-12">
     <h4 style="text-align: center;">
       <input id="ProbeTime" type="hidden" name="input" value="{{trial.ProbeTime}}">
       <img style="width: 224px; height: 224px;" src="{{trial.ProbePath}}" />
     </h4>
   </div>
</div>

<div id="Images" class="row hidden" align="center">
   <div class="col-lg-12">
   <br></br> <br></br> <br></br> <br></br> <br></br> 
   <a href="{{url_for('faces.response',sid=trial.UUID,tid=trial.idTrials,rid=trial.Gallery1ID)}}">
      <button id="button1" type="button" class="btn btn-info">
        <img style="width: 224px; height: 224px; text-align: left;" src="{{trial.Gallery1Path}}" />
      </button>
    </a>
    <a href="{{url_for('faces.response',sid=trial.UUID,tid=trial.idTrials,rid=trial.Gallery2ID)}}">
      <button id="button2" type="button" class="btn btn-info">
        <img style="width: 224px; height: 224px; text-align: center" src="{{trial.Gallery2Path}}" />
      </button>
    </a>
    <a href="{{url_for('faces.response',sid=trial.UUID,tid=trial.idTrials,rid=trial.Gallery3ID)}}">
      <button id="button3" type="button" class="btn btn-info">
        <img style="width: 224px; height: 224px; text-align: right" src="{{trial.Gallery3Path}}" />
      </button>
    </a>
  </div>
</div>

{% endblock %}

web/faces/templates/working.html
{% extends 'layout.html' %}
{% block container %}


<div id="ProbeID" class="hidden">
   <div class="col-lg-12">
     <h4 style="text-align: center;">
      	   <img style="width: 224px; height: 224px;" src="{{trial.ProbePath}}" />
     </h4>
   </div>
</div>


<div id="Images" class="hidden" align="center">
	<a href="{{url_for('faces.response',sid=trial.UUID,tid=trial.idTrials,rid=trial.Gallery1ID)}}">
     	        <input id="Gallery1ID" type="hidden" name="input" value="">
		<button id="button1" type="button" class="btn btn-info">
		<img style="width: 224px; height: 224px; text-align: left;" src="{{trial.Gallery1Path}}" />
		</button>
	</a>

	<a href="{{url_for('faces.response',sid=trial.UUID,tid=trial.idTrials,rid=trial.Gallery2ID)}}">
		<input id="Gallery2ID" type="hidden" name="input" value="">
		<button id="button2" type="button" class="btn btn-info">
		<img style="width: 224px; height: 224px; text-align: center" src="{{trial.Gallery2Path}}" />
	       </button>
	</a>

	 <a href="{{url_for('faces.response',sid=trial.UUID,tid=trial.idTrials,rid=trial.Gallery3ID)}}">
		 <input id="Gallery3ID" type="hidden" name="input" value="">
		 <button id="button3" type="button" class="btn btn-info">
		 <img style="width: 224px; height: 224px; text-align: right" src="{{trial.Gallery3Path}}" />
		 </button>
	 </a>


{% endblock %}